services:
    bot:
        build:
            context: ./
            dockerfile: Dockerfile
        network_mode: host
        restart: unless-stopped
        volumes:
            - "./guilds:/usr/frutbits-voice/guilds"
version: "2.4"